### ISSUE TITLE
Dreo Nomad One S (DR-HTF007S) does not work

### ISSUE THREAD

**Issue by mehulnayak** [zyonse/homebridge-dreo#1]
<html>
<body>

Model DR-HTF007S - Nomad One S does not work
--

<br class="Apple-interchange-newline">
</body>
</html>

**Comment by zyonse** [comment]
Does the homebridge console display any errors?

**Comment by mehulnayak** [comment]
No, I do not see any errors.

**Comment by zyonse** [comment]
Is the fan not responding in homekit? Or does it not show up at all?

**Comment by mehulnayak** [comment]
I just re-configured the it works now. Not sure what did i miss before.
