### ISSUE TITLE
Trying to write a Python Version

### ISSUE THREAD

**Issue by JeffSteinbok** [zyonse/homebridge-dreo#10]
Hi, I'm trying to write a Python version of this for HomeAssistant.
I'm getting this error from the Dreo Servers; wondering if you have any idea, or better yet, is there a way to easily run the TS version you have with Fiddler to see what's going on exactly?

Thanks

{'code': 100030, 'msg': 'Your system clock is incorrect. Please set your clock to the current date and time.'}

2023-06-14 19:54:54,869 - DEBUG - API call URL:
  https://app-api-us.dreo-cloud.com/api/oauth/login
2023-06-14 19:54:54,870 - DEBUG - API call headers:
  {"ua": "dreo/2.0.7 (sdk_gphone64_x86_64;android 13;Scale/2.625)", "lang": "en", "content-type": "application/json; charset=UTF-8", "accept-encoding": "gzip", "user-agent": "okhttp/4.9.1"}
2023-06-14 19:54:54,871 - DEBUG - API call json:
  {"acceptLanguage": "en", "appVersion": "2.8.6", "phoneBrand": "SM N9005", "phoneOS": "Android", "traceId": "1686797694", "client_id": ["7de37c362ee54dcf9c4561812309347a"], "client_secret": ["32dfa0764f25451d99f94e1693498791"], "email": ["REDACT"], "encrypt": ["ciphertext"], "grant_type": ["email-password"], "himei": ["faede31549d649f58864093158787ec9"], "password": "##_REDACTED_##", "scope": ["all"]}
2023-06-14 19:54:54,878 - DEBUG - Starting new HTTPS connection (1): app-api-us.dreo-cloud.com:443
2023-06-14 19:54:55,258 - DEBUG - https://app-api-us.dreo-cloud.com:443 "POST /api/oauth/login?timestamp=1686797694 HTTP/1.1" 200 None
2023-06-14 19:54:55,261 - DEBUG - API response:

  {"code": 100030, "msg": "Your system clock is incorrect. Please set your clock to the current date and time."}

{'code': 100030, 'msg': 'Your system clock is incorrect. Please set your clock to the current date and time.'}
2023-06-14 19:54:55,262 - ERROR - Error logging in with username and password

**Comment by JeffSteinbok** [comment]
Figured it out; Python needs to multiply by 1000 to get ms

**Comment by zyonse** [comment]
Glad you figured it out. Let me know if you have any more questions. I was able to see the app's HTTP requests using Frida and mitmproxy.

**Comment by JeffSteinbok** [comment]
Thanks.  Was really strange; I could use Fiddler proxy to capture most SSL traffic, but for some reason, the Dreo app on iOS said the connection was insecure (all other apps were fine). I'll send you a note (and give credit) once I get things in a better state.  Trying to build an integration (first one) for HomeAssistant.

**Comment by zyonse** [comment]
Yeah the app uses SSL pinning so that's why I had to use Frida

**Comment by JeffSteinbok** [comment]
Got my integration done. Still haven't figured out how to get a packet capture done from the iOS app unfortunately. 

https://github.com/JeffSteinbok/hass-dreo

I did credit your work right at the top. 

Thanks.

**Comment by JeffSteinbok** [comment]
Any chance you'd be willing to help show me how to get packet captures to work via an Android Emulator?  
There are a few things I'd like to dig into a bit more.

Meanwhile, the HomeAssistant version has come along well.  Thanks again for the starting point.

**Comment by zyonse** [comment]
I ran the android studio emulator on my desktop PC and used this guide to set up Frida:
https://httptoolkit.com/blog/frida-certificate-pinning/

On a second computer, I set up mitmproxy and routed traffic from the Android studio emulator from my desktop pc through it.

As long as Frida is set up properly you should be able to see network packets from the Dreo app in the mitmproxy web interface.
