### ISSUE TITLE
What features are expected for a fan?

### ISSUE THREAD

**Issue by Symbiot78** [zyonse/homebridge-dreo#11]
I’ll all info later - but just wondering what is expected from the plugin?

My fan is in the supported list but all I am able to do is turn it off and on. No settings, oscillation or otherwise.

Just wondering if that is the expected behavior?

**Comment by zyonse** [comment]
You should at least be able to control power + fan speed. If your fan supports oscillation it should also show those controls in the home app. What model do you have?

**Comment by Symbiot78** [comment]
It’s the DR-HTF001S

**Comment by Symbiot78** [comment]
oh.. I have NOT added homebridge to apple Home  -  if that makes a difference?

**Comment by Symbiot78** [comment]
Reason for that is I want to add my Dreo to Home assistant

**Comment by Symbiot78** [comment]
ok.. hmm.. so the plot thickens.. 
I added the homebridge & dreo to "home" on my Iphone.
Here the fan works as I had expected.. I can set speed, oscillation etc.

So in homebridge dashboard.. I still cannot.

**Comment by Symbiot78** [comment]
removed it from apple home (deleted homebridge etc in docker) and added it to homeassistant.
in HA I can also only turn on fan and turn off.
only in Apple Home do I have the features shown in the plugin code frontpage.
Very strange.

**Comment by Symbiot78** [comment]
added it to Home assistant. 
If I open the fan entity then I also have all the options (fan speed, on/off, oscillation on/off.)

**Comment by PapiOrtiz** [comment]
> added it to Home assistant. If I open the fan entity then I also have all the options (fan speed, on/off, oscillation on/off.)

Hi - you mind explaining how you were able to achieve this? 
I don't really understand how this "plugin" works & where it is being added. So from there to getting it on Home Assistant, I'm lost.
Appreciate any help

**Comment by Symbiot78** [comment]
Hey

So how far did you get?

**Comment by PapiOrtiz** [comment]
I have the fan + home assistant is set up. 

Part of me thinks feels in order to add the plug in to Home Assistant, I need to add it as an Add-On through the Repository. Am I on to something?

**Comment by Symbiot78** [comment]
You need homebridge .. fx running in docker.

https://hub.docker.com/r/oznu/homebridge/

Then that should be picked up by HomeKit controller integration in HA
In homebridge you add the dreo integration 

HA will pick up the dreo AND the homebridge.

I didn’t add homebridge to HomeKit.. only dreo

**Comment by azalvarez03** [comment]
I'm running into an issue where the fan shows up and I can turn it on/off and control the fan speed but I don't have an option to control oscillation unless I go into the fans additional settings, . My fan is supported (DR-HTF002S). Hopefully I'm just missing a setting and this is an easy problem to fix. attached are screenshots of what I'm talking about.

![IMG_126990FF1AFB-1 2](https://github.com/zyonse/homebridge-dreo/assets/41100041/78a0f26d-5c80-4965-b1af-44bf3ad3bfea)
![IMG_2C5D6B2CC963-1](https://github.com/zyonse/homebridge-dreo/assets/41100041/9b15df77-a3c7-46a7-badd-0b2497318143)

**Comment by Symbiot78** [comment]
@azalvarez03 - same as mine. What is your expectation? What would you like to be different?

**Comment by azalvarez03** [comment]
@Symbiot78 I'm looking to get the oscillation setting in the main settings rather than having to go into additional setting and flipping the toggle to turn oscillation on and off.

**Comment by zyonse** [comment]
> @Symbiot78 I'm looking to get the oscillation setting in the main settings rather than having to go into additional setting and flipping the toggle to turn oscillation on and off.

This is an iOS 17 beta issue. Homebridge exposes the controls to iOS and it's up to Apple to choose how they are displayed.
