### ISSUE TITLE
Dreo Pilot Pro S model DR-HTF005 S

### ISSUE THREAD

**Issue by Jayva2002** [zyonse/homebridge-dreo#12]
**Is your feature request related to a problem? Please describe:**
Anyone know if the Dreo Pilot Pro S model DR-HTF005 S works with this?

**Describe the solution you'd like:**
Someone who knows the answer :)

**Describe alternatives you've considered:**
I am considering buying this model, but don't want to purchase if this isn't going to work with this.

**Additional context:**
Did not see a discussion section.  So asking here.

**Comment by mja00** [comment]
It works, can control speed and oscillation. However for some reason the oscillation toggle doesn't appear next to the fan speed like in the example. I have to go into the accessory settings to toggle it.
