### ISSUE TITLE
Dreo Pilot Max ‎(DR-HTF004) - confirmed working 

### ISSUE THREAD

**Issue by axlwinter** [zyonse/homebridge-dreo#14]
Thanks for this plugin! It's awesome and I am so happy to finally have support for my Dreo fans in Homebridge.

I just wanted to let you know that I have tried this with Dreo Pilot Max S (‎DR-HTF004) and it works beautifully including oscillation.

**Comment by zyonse** [comment]
Thanks for the feedback!
