### ISSUE TITLE
Fan Speed and Oscillation

### ISSUE THREAD

**Issue by RadDip** [zyonse/homebridge-dreo#17]
**Describe The Bug:**
Just purchased the DR-HAF003S.  1. The fan speed in HomeKit does not match the fan speed when changed on the fan, via the fan remote or via Alexa.  2. I have no oscillation controls in HomeKit

**To Reproduce:**
Control of fan locally, via remote or via Alexa

**Expected behavior:**
The same fan speed value set locally via the fan, fan remote or Alexa would be accurately represented in the HomeKit setting

**Logs:**
No logs representing anything
```
Show the Homebridge logs here, remove any sensitive information.
```

**Plugin Config:**

```json
Show your Homebridge config.json here, remove any sensitive information.
"platform": "DreoPlatform",
    "name": "Dreo Platform",
    "options": {
        "email": "",
        "password": ""

**Screenshots:**
<!-- If applicable, add screenshots to help explain your problem. -->

**Environment:**
Homekit iOS 16.6

* **Plugin Version**: 2.1.0
* **Homebridge Version**: <!-- homebridge -V -->  Hoobs 4.3.0 running Homebridge Version 1.6.0
* **Node.js Version**: <!-- node -v --> 16.20.2
* **NPM Version**: <!-- npm -v -->
* **Operating System**: <!-- Raspbian / Ubuntu / Debian / Windows / macOS / Docker / hb-service --> Debian running on Raspberry Pi Model 4B with 4GB RAM

<!-- Click the "Preview" tab before you submit to ensure the formatting is correct. -->

**Comment by zyonse** [comment]
What iOS version?

**Comment by RadDip** [comment]
iOS 16.6

**Comment by zyonse** [comment]
Can you restart homebridge in debug mode (can be enabled in homebridge settings) and paste the console output here? Make sure you redact any sensitive info as needed.

**Comment by RadDip** [comment]
Tried every command to get Hoobs into debug mode and nothing worked.   Did upgrade to your version 3.0.  Percent slider still does not accurately represent the fan speed number shown on fan.  Still no separate oscillation controls

**Comment by zyonse** [comment]
I haven't used Hoobs before so it's hard for me to provide specific support for it. Can you try setting up the fan with Homebridge to see if the issues persist?

Also when you say the percent slider isn't accurate, what specific issue are you having? My fan has speeds 1-6 represented as 17%, 33%, 50%, etc.

**Comment by RadDip** [comment]
Hello Gavin:

I appreciate you responding back.   As you may be aware Hoobs is simply an interface platform that is wrapped around homebridge.  The core of system is in fact homebridge and operates as homebridge.   In fact, your plugin app is on the approved list for Hoobs (for what that is worth).

Since Hoobs is the environment that I work within, it would defeat the purpose of me trying to test this in just the homebridge ecosystem.  Besides the fact that it would be very time consuming for me to do so.

As for the % slider; I don't feel that that is an accurate representation of the fan speed since the fan itself lists the fan speeds in whole numbers ie, 1,2,3,4,5,6, etc physically right on the fan itself.     Additionally, with the % slider in use it does skip some fan speeds on the fan, ie I cannot get to speed 4 (which I use a lot).  The slider goes from 38% and jumps to 50% which misses fan speed 4 on my fan.

As well there is still no oscillation selection icon shown in homekit.

Thank you,

Rich

**Comment by zyonse** [comment]
The slider being percent-based is unfortunately an Apple HomeKit limitation. However, you should still be able to set all of your fan's factory speed values. Did you have this issue on v2.1.0? I changed the fan speed behavior a bit in v3.0.0.

In order to address the oscillation issue, I need logs similar to those shown [here](https://github.com/zyonse/homebridge-dreo/issues/5#issuecomment-1575374387).

**Comment by zyonse** [comment]
Also, how many speeds does your fan have?

**Comment by RadDip** [comment]
Have always had the issue of the slider not being accuracy not corresponding to the fan speed.  That was the impetus for the issue that I had opened (besides no oscillation slider).   The fan speeds range from 1-8 plus off.   

Unfortunately, I am not able to get hoobs into debug mode despite all my efforts.  None of the commands seem to work in the SSL Terminal
