### ISSUE TITLE
DR-HPF002S Support for Oscillation and Turbo Mode

### ISSUE THREAD

**Issue by harvindhillon** [zyonse/homebridge-dreo#38]
**Is your feature request related to a problem? Please describe:**
DR-HPF002S is supported by the plugin but missing Oscillation support & Turbo Mode

**Describe the solution you'd like:**
Ability to control left/right & up/down Oscillation as well as the angles.
Ability to enable/disable turbo mode

**Describe alternatives you've considered:**
None yet

**Additional context:**
None

**Comment by zyonse** [comment]
You should be able to control oscillation if you go Device settings > Accessories > Fan > Settings. The setting got buried in a recent iOS update but it should still be visible.

**Comment by harvindhillon** [comment]
Apologies @zyonse, I should mention I'm using homebridge docker container. I don't see the option. Might be a homebridge issue? i only have on off and speed control from the dashboard 

![image](https://github.com/zyonse/homebridge-dreo/assets/95908970/2dd7dadd-7752-4e4d-b5eb-14c31365873f)

**Comment by zyonse** [comment]
It doesn't show the oscillation option in the dashboard.

**Comment by harvindhillon** [comment]
Ah okay, I use it mainly with Home Assistant to pull in devices that dont natively work as I dont really have any ios devices. Shame I dont see the options exposed to Home Assistant as well.

Thanks for the explanation.

**Comment by zyonse** [comment]
Have you tried the Dreo Home Assistant integration by Jeff Steinbok?

**Comment by harvindhillon** [comment]
Hi,

I actually do, unfortunately he hasnt added support for this fan yet. I have another DR-HAF003S that works with the integration.
I have a new feature ticket open there too but I went the homebridge plugin route until that was supported.

I was already using this bridge to pull in my VeSync air purifiers as well which dont support EU versions natively on Home Assistant.

**Comment by zyonse** [comment]
Can you test the latest version to see if oscillation shows up in Home Assistant?

**Comment by harvindhillon** [comment]
Thanks, I'm currently on my summer break till end July. I'll report as soon as I get the chance. Thanks for looking into this. Much appreciated.

**Comment by zyonse** [comment]
Feel free to comment on this issue if you're still having the same problem when you get home. Closing to reduce clutter.

**Comment by harvindhillon** [comment]
Hi @zyonse,

Yes I see the option now when I click on power. It has yes/no under oscillation :)
