### ISSUE TITLE
add support for DR-HPF005S natural mode and left right and up down tilt

### ISSUE THREAD

**Issue by Sebastian-blu** [zyonse/homebridge-dreo#42]
**Is your feature request related to a problem? Please describe:**
Hi hi 
I just installed and the fan speed and temp seems to work with this model number, but was hoping u could add vertical and horizontal oscillation controls. and ability to turn natural mode on and off. The app has different preset angles for ocilation limits if adding sliders for that doesn't work

Thanks for making this 

![IMG_4DDFD2751A2B-1](https://github.com/zyonse/homebridge-dreo/assets/28813706/7c65eb80-2285-4053-acaf-4c40216b04ec)
![IMG_17658AFBDA62-1](https://github.com/zyonse/homebridge-dreo/assets/28813706/76188f7d-757a-456c-bf30-4153f4a4a45d)

**Comment by zyonse** [comment]
Unfortunately HomeKit doesn't support these kinds of specific oscillation controls natively. https://developers.homebridge.io/#/service/Fanv2
