### ISSUE TITLE
Support for DR-HTF009S (Cruiser Pro T2S) tower fan

### ISSUE THREAD

**Issue by timwoodland** [zyonse/homebridge-dreo#44]
**Is your feature request related to a problem? Please describe:**
Please add support for ‎DR-HTF009S (Cruiser Pro T2S) tower fan

**Describe the solution you'd like:**
The fan speed control currently works for this device but other settings such as oscillation do not

**Comment by zyonse** [comment]
Can you provide a screenshot? Oscillation should be in device settings > accessories > fan > settings. Unfortunately Apple buried it in this menu in iOS 17.

**Comment by timwoodland** [comment]
Wow I cannot believe how hard Apple has made that. I am sorry I completely missed it. So, yes I can confirm that I can indeed access the Oscillate toggle. Sorry to have wasted your time
![Screenshot 2024-07-20 at 20 05 04](https://github.com/user-attachments/assets/cd8f6423-024b-4329-be6e-9c2319bcf4f3)
