### ISSUE TITLE
Please add additional support for the DR-HTF008S (Cruiser Pro T3 S)

### ISSUE THREAD

**Issue by gradyhouston** [zyonse/homebridge-dreo#45]
**Is your feature request related to a problem? Please describe:**
No.

**Describe the solution you'd like:**
Additional support for the DR-HTF008S (Cruiser Pro T3 S) - oscillation control and temperature reading within the Home App.

**Describe alternatives you've considered:**
N/A

**Additional context:**
This model is seen by the plugin and does work but it only has basic on/off and fan speed function within the Home App.

**Comment by gradyhouston** [comment]
> This works out of the box with v3.3.0 of the plugin. The oscillation control and the temperature reading are within the accessories option in the home app for the device.

I'm on the latest version (3.3.0) and do not see the oscillation control in the accessories section for the device in the home app . I have two of these same devices and both of them only show fan speed and temperature reading.

![IMG_5490](https://github.com/user-attachments/assets/29937745-b82b-48a4-9ce9-f1f9373a7727)

**Comment by gradyhouston** [comment]
> Open the fan device and go to its settings, the oscillation toggle should be there. Unfortunately Apple made it a lot more hidden in iOS 17.

The screenshot I posted was from the settings of the device. Long press on the device -> Accessory Settings -> Accessories.

Where else should I look?

**Comment by zyonse** [comment]
Open the fan accessory from that menu and go to its settings.

**Comment by gradyhouston** [comment]
> Open the fan accessory from that menu and go to its settings.

Oh, wow! I would have never found this. They did bury it in iOS17.

Thank you!
