### ISSUE TITLE
Ceiling fan support (‎CLF-712S)

### ISSUE THREAD

**Issue by raven77m** [zyonse/homebridge-dreo#49]
Any luck with getting the light to work?  The fan is working great.  
Hopefully, eventually we (you) can get the RGB lights working to. 

😀 

Thank you for all your hard work!

**Comment by zyonse** [comment]
Duplicate of #39

**Comment by raven77m** [comment]
> Duplicate of #39 

My bad.   Sorry.  
I did see that, but I thought it was a different model fan. 

Thanks!!
