### ISSUE TITLE
Plugin intermittently interferes with DREO App

### ISSUE THREAD

**Issue by Gyre1** [zyonse/homebridge-dreo#52]
**Describe The Bug:**
DREO app is occasionally unresponsive when accessing individual fan controls while plugin is active.

**To Reproduce:**
Use this DREO homebridge plugin and the iOS DREO app. 
Access different DREO devices. Occasionally, when selecting a device in the app, the app will attempt to contact the device for a very long time without success. This never happens in the absence of the plugin.

**Expected behavior:**
I expected the iOS app to respond right away as it always did in the past. Somehow the connection is being dominated by the plugin.

**Logs:**

```
Show the Homebridge logs here, remove any sensitive information.
```

**Plugin Config:**

```{
    "name": "Dreo Platform",
    "options": {
        "email": "[redacted]",
        "password": "[redacted]"
    },
    "hideTemperatureSensor": false,
    "temperatureOffset": 0,
    "platform": "DreoPlatform"
}
```

**Screenshots:**

**Environment:**

* **Plugin Version**: 3.3.3
* **Homebridge Version**: 1.8.4
* **Node.js Version**: 20.17.0
* **NPM Version**: 
* **Operating System**: Homebridge on Synology Docker (Ubuntu Jammy (22.04.4 LTS)) and iOS 17 and 18.

**Comment by zyonse** [comment]
Can you roll back to v3.3.2 and check if the issue still occurs?

**Comment by Gyre1** [comment]
Will do.

**Comment by Gyre1** [comment]
I rolled back to 3.3.2 - no improvement.
I disabled the plugin - no improvement.
I uninstalled the plugin - app works normally.

Very odd that simply having the app installed and disabled still causes
interference.

**Comment by zyonse** [comment]
Disabling the plugin should have the same effect as uninstalling it. Does this happen if the iPhone is on cellular?

**Comment by Gyre1** [comment]
I’m beginning to think the app is a bit flaky about establishing
communication with the fans. I’ll try to do some back to back testing.

**Comment by Gyre1** [comment]
Looks like the app is just a bit quirky about establishing connection to
the fans. I no longer think the homebridge plugin has anything to do with
it.

**Comment by zyonse** [comment]
Thanks for the update
