### ISSUE TITLE
Support for Polyfan 513S?

### ISSUE THREAD

**Issue by glitchykitten** [zyonse/homebridge-dreo#60]
Any chance you could add support for the Polyfan 513S currently available on Amazon?  I'd be willing to help or sponsor a bit if that makes a difference?

**Comment by zyonse** [comment]
Have you tested it? It looks like it *should* work with the plugin

**Comment by glitchykitten** [comment]
Well...  I installed the plug in and it loads fine but I don't see any accessories.  Maybe there's more configuration I'm not realizing I need to do?

**Comment by glitchykitten** [comment]
Oh hold on... maybe I messed something up.  I'll update shortly.

**Comment by glitchykitten** [comment]
Doh.... user error!!!  I'm sorry.  :)

**Comment by zyonse** [comment]
No worries, glad it's working!
