### ISSUE TITLE
Add Support for Humidifier DR-HHM001S

### ISSUE THREAD

**Issue by straushaus1** [zyonse/homebridge-dreo#62]
**Is your feature request related to a problem? Please describe:**
Not a problem, just getting the error: 
[01/12/2024, 17:16:28] [Dreo Platform] Adding new accessory: Humidifier
[01/12/2024, 17:16:28] [Dreo Platform] Humidifier not yet supported

**Describe the solution you'd like:**
I'd love to see the addition of the humidifier to the list of supported accessories.

**Describe alternatives you've considered:**
No other plugins for DREO seem to exist in the same capacity that this one does.

**Comment by zyonse** [comment]
Duplicate of #28
